version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production  # This should be "production" for deployment
      - NEXT_PUBLIC_API_URL=http://backend:5000
    command: ["sh", "-c", "npm run build && npm run start"]

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "5000:5000"
    volumes:
      - ./src/backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=songRecAlgorithm.py
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]

