services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: python_backend
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
    env_file: ".env"
