services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: python_backend
    ports:
      - "5001:5001"
    volumes:
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
