services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - ./src/frontend:/service
      - /service/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5001
    depends_on:
      - backend
    # command: ["sh", "-c", "npm run dev"]

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
      args:
        - TARGETARCH=${TARGETARCH:-}  # Pass architecture as build arg
    container_name: python_backend
    ports:
      - "5001:5001"
    volumes:
      - ./src/backend:/service
      - /service/__pycache__
    environment:
      - FLASK_ENV=development
      - FLASK_APP=wsgi.py
      - FLASK_DEBUG=1 
    platform: ${DOCKER_PLATFORM:-}  # Will be empty unless set
    # command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]

# Conditional platform logic
x-platform: &platform
  linux/amd64: &force-amd64
    condition: ${DOCKER_PLATFORM:-} == "linux/amd64"

