services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5001
    command: ["sh", "-c", "pnpm dev"]
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: python_backend
    ports:
      - "5001:5001"
    volumes:
      - ./.env:/app/.env
    environment:
      - FLASK_ENV=development
