services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs_app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./db.db:/app/db.db
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:5001
    command: ["sh", "-c", "pnpm dev"]
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: python_backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
      - ./db.db:/app/db.db
    environment:
      - FLASK_ENV=development
      - FLASK_APP=flaskTest.py
    command: ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]
