name: Build, Push, and Deploy DJ Song Match

on:
  push:
    branches:
      - main
      - gha-deploy-to-home-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build images with Docker Compose
        run: docker compose -f ./docker-compose.yml build

      - name: Push images to Docker Hub
        run: docker compose -f ./docker-compose.yml push

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Windows 11 Home Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.WINDOWS_PASSWORD }}
          port: 22
          script: |
            cd C:\Users\Madi\djsongmatch
            git pull origin main
            docker compose pull
            docker compose down
            docker compose up -d
