name: Build, Push, and Deploy DJ Song Match

on:
  push:
    branches:
      - main
      - gha-deploy-to-home-server

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and tag images with Docker Compose
        run: docker-compose build

      - name: Tag and push individual images
        run: |
          docker tag dj-song-match-backend ${{ secrets.DOCKERHUB_USERNAME }}/djsongmatch-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/djsongmatch-backend:latest

          docker tag dj-song-match-frontend ${{ secrets.DOCKERHUB_USERNAME }}/djsongmatch-frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/djsongmatch-frontend:latest
