name: Deploy DJ Song Match to Home Server

on:
  push:
    branches:
      - main
      - gha-deploy-to-home-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Windows 11 Home Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.WINDOWS_PASSWORD }}
          port: 22
          script: |
            cmd.exe /c "
              cd C:\Users\Madi\djsongmatch &&
              git pull origin gha-deploy-to-home-server &&
              docker compose down &&
              docker compose build &&
              docker compose up -d
            "

